package com.dip.unifiedviewer.constansts;

public interface ApiExposureConstants {
    String REQUEST_TYPE_NID = "NID";
    String REQUEST_TYPE_ESAF = "ESAF";
    String REQUEST_TYPE_PASSPORT = "PASSPORT";
    String REQUEST_TYPE_DRIVING_LICENSE = "DRIVINGLICENSE";
    String REQUEST_TYPE_VEHICLE_REGISTRATION = "VEHICLEREGISTRATION";
    String REQUEST_TYPE_MSISDN = "MSISDN";
    String REQUEST_TYPE_LRL = "LRL";
    String REQUEST_TYPE_SMS = "SMS";
    String REQUEST_TYPE_CDR = "CDR";
    String REQUEST_TYPE_MOBILE_DEVICE_INFORMATION = "MOBILE_DEVICE_INFORMATION";
    String REQUEST_TYPE_BIRTH_REGISTRATION = "BIRTHREGISTRATION";
    String REQUEST_TYPE_LOCAL_ESAF = "LOCAL_ESAF";
    String REQUEST_TYPE_LOCAL_ESAF_THEN_ESAF = "LOCAL_ESAF_THEN_ESAF";
    String REQUEST_TYPE_MNP = "MNP";
    String REQUEST_TYPE_PSTN_MSISDN = "PSTN_MSISDN";
    String REQUEST_TYPE_PSTN_ESAF = "PSTN_ESAF";
    String REQUEST_TYPE_NBR = "NBR";

    String REQUEST_TYPE_EDUCATION_BOARD = "EDUCATION_BOARD";
    String STRING_SEPERATOR = ", ";

    String DATE_FORMAT = "yyyy-MM-dd";

    int DEFAULT_TIME_RANGE_IN_DAYS = 7;

    String LOG_KEY_REQUEST_ID = "request_id";
    String UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";
    String NOT_FOUND = "NOT_FOUND";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String PARENT_RULE_FAILED = "PARENT_RULE_FAILED";
    String REQUEST_TIMEOUT = "REQUEST_TIMEOUT";
}
